#include <bits/stdc++.h>
using namespace std;
int n, k, u, v, l, r;
vector <int> a, b;

vector <int> ()

int cycle(vector <int> x, vector <int> y) {
    int d = 0;
    while (1){
        x = 
    }
}

int main() {
    cin >> n >> l >> u >> v >> l >> r;
    a.resize(n + 1); b.resize(n + 1);
    for (int i = 1; i <= n; i++) {
        a[i] = i;
        b[i] = i;
    }
    int d = chuki(a, b);
    return 0;
}